version: '3.8'

services:
  database-technical-intelligence:
    container_name: database-technical-intelligence
    image: postgres:12
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./scripts/create_database.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - '5432'
    environment:
      - POSTGRES_DB=technical_intelligence_database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5439:5432'
    networks:
      - technical-intelligence

networks:
  technical-intelligence:
    name: technical-intelligence-database
    driver: bridge